version: '3'

services:
    server: 
        build: ./server
        ports:
            - "80:3000" 

    camera_1:
        environment:
            - CAMERA_ID=camera_1
            - CAMERA_NAME=Conference Room
        build: ./client_camera      

    camera_2:
        environment:
            - CAMERA_ID=camera_2
            - CAMERA_NAME=Loading Dock
        build: ./client_camera      
